manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
  projects:
    - name: zephyr
      url: git@github.com:mczerski/zephyr.git
      revision: a81b9eb5c571412a268d925884be5791423fe825
      west-commands: scripts/west-commands.yml
      import:
        name-allowlist:
          - cmsis_6
          - hal_nordic
          - picolibc
    - name: ncs-zigbee
      repo-path: ncs-zigbee
      remote: ncs
      revision: v1.4.0
      import:
        name-allowlist:
          # Core repositories
          - nrf
          - zephyr
          # Zephyr modules
          - cmsis_6
          - hal_nordic
          - picolibc
          #- zcbor               # used by MCUboot serial recovery / mcumgr
          # Crypto
          - mbedtls
          - oberon-psa-crypto
          - nrfxlib
          # Bootloader
          #- mcuboot
  self:
    path: zigbee-scene-controller
